Update org
ncskier/stackstorm-github pull request #15
Opened 2020-08-10 17:14 UTC by makandre

2020-08-10 21:06 UTC, akihikokuroda commented on actions/register_org.py
> +
Extra chars.

2020-08-10 21:42 UTC, akihikokuroda commented on actions/register_org.py
> +        return list(filter_orgs(dict))
I think that it's better to return the new or updated entry only.

2020-08-10 21:43 UTC, akihikokuroda commented on actions/delete_registered_org.py
> +        return list(filter_orgs(dict))
I think that it's better to return the deleted entry only.

2020-08-10 21:43 UTC, akihikokuroda requested changes
Looks good.  Thanks.  I have comments about the return values.

2020-08-11 11:47 UTC, makandre commented
I've made the suggested changes

2020-08-11 12:22 UTC, akihikokuroda approved these changes
Andrew, looks good.  Thanks.

2020-08-11 12:24 UTC, merged